#include"configure.hpp"
#include"define/base_type.hpp"
#include"macro/xdebug+.hpp"
#include"macro/xexport.hpp"
#include"macro/xhint.hpp"
#include"macro/xinterface.hpp"
#include"macro/xstruct.hpp"
#include"memop/addressof.hpp"
