#pragma once
#include"macro/xnt.hpp"
#define __xlist_fields(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60,a61,a62,a63,...)    \
__xheader_fields_ ## a0      \
__xget_fields_ ## a1         \
__xget_fields_ ## a2         \
__xget_fields_ ## a3         \
__xget_fields_ ## a4         \
__xget_fields_ ## a5         \
__xget_fields_ ## a6         \
__xget_fields_ ## a7         \
__xget_fields_ ## a8         \
__xget_fields_ ## a9         \
__xget_fields_ ## a10        \
__xget_fields_ ## a11        \
__xget_fields_ ## a12        \
__xget_fields_ ## a13        \
__xget_fields_ ## a14        \
__xget_fields_ ## a15        \
__xget_fields_ ## a16        \
__xget_fields_ ## a17        \
__xget_fields_ ## a18        \
__xget_fields_ ## a19        \
__xget_fields_ ## a20        \
__xget_fields_ ## a21        \
__xget_fields_ ## a22        \
__xget_fields_ ## a23        \
__xget_fields_ ## a24        \
__xget_fields_ ## a25        \
__xget_fields_ ## a26        \
__xget_fields_ ## a27        \
__xget_fields_ ## a28        \
__xget_fields_ ## a29        \
__xget_fields_ ## a30        \
__xget_fields_ ## a31        \
__xget_fields_ ## a32        \
__xget_fields_ ## a33        \
__xget_fields_ ## a34        \
__xget_fields_ ## a35        \
__xget_fields_ ## a36        \
__xget_fields_ ## a37        \
__xget_fields_ ## a38        \
__xget_fields_ ## a39        \
__xget_fields_ ## a40        \
__xget_fields_ ## a41        \
__xget_fields_ ## a42        \
__xget_fields_ ## a43        \
__xget_fields_ ## a44        \
__xget_fields_ ## a45        \
__xget_fields_ ## a46        \
__xget_fields_ ## a47        \
__xget_fields_ ## a48        \
__xget_fields_ ## a49        \
__xget_fields_ ## a50        \
__xget_fields_ ## a51        \
__xget_fields_ ## a52        \
__xget_fields_ ## a53        \
__xget_fields_ ## a54        \
__xget_fields_ ## a55        \
__xget_fields_ ## a56        \
__xget_fields_ ## a57        \
__xget_fields_ ## a58        \
__xget_fields_ ## a59        \
__xget_fields_ ## a60        \
__xget_fields_ ## a61        \
__xget_fields_ ## a62        \
__xget_fields_ ## a63        \

#define xlist_fields(...)   __xlist_fields(__VA_ARGS__,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,)
